title: Alejandro's Blog
email: blog@avaldes.co
description: >- # this means to ignore newlines until "baseurl:"
  Stories and adventures in software development.
baseurl: ""
url: "https://avaldes.co"
name: Alejandro Valdés
tagline: Software Developer
repository: "alevalv/alevalv.github.io"
breadcrumbs: true
remote_theme: "fongandrew/hydeout"
author:
  name: "Alejandro Valdés"
  bio: "Yet Another Software Developer Blog"
  avatar: "/assets/images/bio-photo.jpg"
  location : "Colombia"
  type: Person
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alevalv"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alevalv"

footer:
  links:
    - label: "GPG Key"
      icon: "fas fa-key"
      url: "https://avaldes.co/alevalv.asc"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alevalv"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alevalv"

include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn

# Liquid
strict_front_matter: true
liquid:
  error_mode: strict

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

paginate: 5

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
